version: '3.7'

services:
    # サービス名は自由に設定
    django:
        # appディレクトリの中から`Dockerfile`を探す
        build: ./django_project
        # サービス起動後に入力されるコマンドを設定
        command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
        # データを永続化させる場合の設定。`host:container`でパスを記載
        volumes:
            - ./django_project/:/usr/src/django_project/
        # 開放するポートを指定。`host:container`でポートを記載
        ports:
            - 8000:8000
        # 環境変数を指定
        environment:
            # 1ならデバックモード
            - DEBUG=1
            # setting.pyに記載されているSECRET_KEYを記入
            - SECRET_KEY=hoge
        # djangoサービスをdbサービス起動後に立ち上げる
        depends_on:
            - db

    db:
        image: mysql:8.0
        restart: always
        # su権限を持つ、指定されたユーザーと同じ名前のデータベースを作成
        # valueはdjangoサービスで指定したものと同じ様に記載する
        environment:
            #コンテナ内のMySQLを起動する際のパスワードを設定
            - MYSQL_ROOT_PASSWORD=root1234
            - MYSQL_USER=django
            - MYSQL_PASSWORD=django
            - MYSQL_DB=anime_db
            - TZ='Asia/Tokyo'
        # サービス起動時、unicodeがlatin1のため、utf-8に変更する
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        ports:
            - 33306:3306

# トップレベルに書く「名前付きvolumes」は複数サービスから参照できる
volumes:
    mysql_data:
